config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-carmine-uguisu.sh
        container: qc.acc_ugly-brass-gerbil
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-orchid-owl.sh
        container: qc.doc_lanky-orange-dragon
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-corn-numbat.sh
        container: qc.doc_snappy-russet-hyena
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-harlequin-bloodhound.sh
        container: qc.doc_randy-razzmatazz-giraffe
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-orange-gibbon.sh
        container: qc.lic_thirsty-champagne-bison
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-pear-sparrow.sh
        container: qc.sec_cranky-chartreuse-toad
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-sapphire-rhinoceros.sh
        container: qc.sty_trippy-yellow-woodlouse
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-aqua-squirt.sh
        container: qc.ver_flimsy-lavender-axolotl
timeout: 1800
