config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/eosc-synergy/saps-catalog
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-periwinkle-guppy.sh
        container: qc.acc_scaly-cyan-coral
  QC.Doc:
    repos:
      github.com/eosc-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-grey-coyote.sh
        container: qc.doc_cloudy-razzmatazz-cassowary
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ivory-vole.sh
        container: qc.doc_slaphappy-jade-insect
      github.com/eosc-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-burgundy-starfish.sh
        container: qc.doc_homely-tomato-sponge
  QC.Lic:
    repos:
      github.com/eosc-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-platinum-mongrel.sh
        container: qc.lic_cranky-bronze-coral
  QC.Sec:
    repos:
      github.com/eosc-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-persimmon-starfish.sh
        container: qc.sec_queasy-bronze-cattle
  QC.Sty:
    repos:
      github.com/eosc-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-maroon-lizard.sh
        container: qc.sty_scaly-pumpkin-oyster
  QC.Ver:
    repos:
      github.com/eosc-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-pink-capybara.sh
        container: qc.ver_woolly-charcoal-swan
timeout: 1800
