config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/eosc-synergy/saps-catalog
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-khaki-grasshopper.sh
        container: qc.acc_beady-brass-koala
  QC.Doc:
    repos:
      github.com/eosc-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-aqua-caracal.sh
        container: qc.doc_slimy-razzmatazz-beagle
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-orchid-urchin.sh
        container: qc.doc_stealthy-white-butterfly
      github.com/eosc-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-sangria-wolfhound.sh
        container: qc.doc_whiny-beige-retriever
  QC.Lic:
    repos:
      github.com/eosc-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-rose-buzzard.sh
        container: qc.lic_crappy-brass-fox
  QC.Sec:
    repos:
      github.com/eosc-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-eggplant-lemur.sh
        container: qc.sec_muzzy-auburn-guppy
  QC.Sty:
    repos:
      github.com/eosc-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-corn-spoonbill.sh
        container: qc.sty_bumpy-mustard-crab
  QC.Ver:
    repos:
      github.com/eosc-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-dandelion-crane.sh
        container: qc.ver_geeky-orchid-centipede
timeout: 1800
