config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-vermilion-llama.sh
        container: qc.acc_sickly-periwinkle-gorilla
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-sangria-jackal.sh
        container: qc.doc_surly-tangerine-gopher
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-burgundy-affenpinscher.sh
        container: qc.doc_boozy-tan-cichlid
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-coral-dingo.sh
        container: qc.doc_stuffy-bistre-monkey
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-green-rattlesnake.sh
        container: qc.lic_shaky-cornflower-bordeaux
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-viridian-collie.sh
        container: qc.sec_zippy-cinnamon-beagle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-rust-lion.sh
        container: qc.sty_lanky-fuchsia-jaguar
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-chestnut-fossa.sh
        container: qc.ver_gamy-carmine-dragon
timeout: 1800
