config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-goldenrod-flounder.sh
        container: qc.acc_sunny-mauve-buffalo
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cerise-labradoodle.sh
        container: qc.doc_messy-malachite-coral
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-indigo-chihuahua.sh
        container: qc.doc_queasy-harlequin-sloth
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-rose-chin.sh
        container: qc.doc_woolly-auburn-hyena
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-aqua-gorilla.sh
        container: qc.lic_lousy-ultramarine-jackal
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-flax-dunker.sh
        container: qc.sec_jumpy-apricot-dollar
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-champagne-bulldog.sh
        container: qc.sty_sleepy-zucchini-vole
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-eggplant-rhinoceros.sh
        container: qc.ver_flabby-sepia-quoll
timeout: 1800
