config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/eosc-synergy/saps-catalog
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-violet-rat.sh
        container: qc.acc_sleepy-amethyst-bullfrog
  QC.Doc:
    repos:
      github.com/eosc-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cornflower-frise.sh
        container: qc.doc_frumpy-magnolia-warthog
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-amaranth-macaque.sh
        container: qc.doc_freaky-cardinal-ocelot
      github.com/eosc-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-violet-koala.sh
        container: qc.doc_homey-cream-penguin
  QC.Lic:
    repos:
      github.com/eosc-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-teal-starfish.sh
        container: qc.lic_trippy-grey-chinchilla
  QC.Sec:
    repos:
      github.com/eosc-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-aqua-hound.sh
        container: qc.sec_cranky-wheat-corgi
  QC.Sty:
    repos:
      github.com/eosc-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-asparagus-mastiff.sh
        container: qc.sty_lumpy-emerald-tiger
  QC.Ver:
    repos:
      github.com/eosc-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-chestnut-cat.sh
        container: qc.ver_flaky-emerald-devil
timeout: 1800
