config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-smalt-caiman.sh
        container: qc.acc_seedy-salmon-anteater
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cobalt-wildebeest.sh
        container: qc.doc_jumpy-mustard-wallaby
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-mauve-zonkey.sh
        container: qc.doc_snappy-aquamarine-panda
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-saffron-bear.sh
        container: qc.doc_tasty-ivory-binturong
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-puce-walrus.sh
        container: qc.lic_sleazy-salmon-axolotl
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-aqua-chamois.sh
        container: qc.sec_squeaky-plum-retriever
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-indigo-capybara.sh
        container: qc.sty_sunny-mustard-mammoth
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-vermilion-flamingo.sh
        container: qc.ver_homey-plum-cuscus
timeout: 1800
