config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/eosc-synergy/saps-catalog
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-vermilion-setter.sh
        container: qc.acc_crappy-cerulean-dunker
  QC.Doc:
    repos:
      github.com/eosc-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cinnabar-tarantula.sh
        container: qc.doc_sloppy-buff-walrus
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-harlequin-leopard.sh
        container: qc.doc_bumpy-amaranth-mule
      github.com/eosc-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-dandelion-drever.sh
        container: qc.doc_snoopy-razzmatazz-rottweiler
  QC.Lic:
    repos:
      github.com/eosc-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-copper-dogfish.sh
        container: qc.lic_ugly-amethyst-akbash
  QC.Sec:
    repos:
      github.com/eosc-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-lilac-monster.sh
        container: qc.sec_slimy-orange-toad
  QC.Sty:
    repos:
      github.com/eosc-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-rose-dachshund.sh
        container: qc.sty_crabby-jade-ray
  QC.Ver:
    repos:
      github.com/eosc-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-chestnut-dollar.sh
        container: qc.ver_scaly-blue-heron
timeout: 1800
