config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/eosc-synergy/saps-catalog
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lime-gharial.sh
        container: qc.acc_leaky-cerise-lynx
  QC.Doc:
    repos:
      github.com/eosc-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-red-squirt.sh
        container: qc.doc_sickly-viridian-caracal
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-blue-wolverine.sh
        container: qc.doc_woolly-vermilion-bonobo
      github.com/eosc-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cyan-ray.sh
        container: qc.doc_lousy-puce-guppy
  QC.Lic:
    repos:
      github.com/eosc-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-russet-cheetah.sh
        container: qc.lic_scaly-emerald-duck
  QC.Sec:
    repos:
      github.com/eosc-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cinnamon-bear.sh
        container: qc.sec_skinny-magnolia-goat
  QC.Sty:
    repos:
      github.com/eosc-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.silly-buff-cougar.sh
        container: qc.sty_snoopy-magenta-bombay
  QC.Ver:
    repos:
      github.com/eosc-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-pear-bloodhound.sh
        container: qc.ver_skanky-purple-jackal
timeout: 1800
