config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/style_tools
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/eosc-synergy/saps-catalog
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-crimson-greyhound.sh
        container: qc.acc_clammy-lemon-dingo
  QC.Doc:
    repos:
      github.com/eosc-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-beige-zebu.sh
        container: qc.doc_crabby-malachite-cattle
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-lemon-russel.sh
        container: qc.doc_scummy-ruby-barnacle
      github.com/eosc-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-white-uguisu.sh
        container: qc.doc_woolly-carmine-dog
  QC.Lic:
    repos:
      github.com/eosc-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-copper-weasel.sh
        container: qc.lic_frumpy-asparagus-wolf
  QC.Sec:
    repos:
      github.com/eosc-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-black-zebu.sh
        container: qc.sec_goopy-persimmon-tapir
  QC.Sty:
    repos:
      github.com/eosc-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-asparagus-raccoon.sh
        container: qc.sty_snippy-cerise-labradoodle
      github.com/eosc-synergy/saps-catalog pycodestyle:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-olive-whippet.sh
        container: qc.sty_tasty-peach-moorhen
      github.com/eosc-synergy/saps-catalog pylint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-viridian-snake.sh
        container: qc.sty_freaky-tan-quokka
  QC.Ver:
    repos:
      github.com/eosc-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-champagne-lemur.sh
        container: qc.ver_leaky-pumpkin-shrimp
timeout: 1800
