config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/eosc-synergy/saps-catalog
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-myrtle-barracuda.sh
        container: qc.acc_foggy-black-oriole
  QC.Doc:
    repos:
      github.com/eosc-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-green-horse.sh
        container: qc.doc_shaggy-sepia-jellyfish
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-blue-avocet.sh
        container: qc.doc_sickly-thistle-capuchin
      github.com/eosc-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-asparagus-buffalo.sh
        container: qc.doc_lousy-denim-woodpecker
  QC.Lic:
    repos:
      github.com/eosc-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-aqua-mastiff.sh
        container: qc.lic_snazzy-gamboge-mule
  QC.Sec:
    repos:
      github.com/eosc-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-beige-wallaby.sh
        container: qc.sec_bumpy-ecru-fousek
  QC.Sty:
    repos:
      github.com/eosc-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-periwinkle-quokka.sh
        container: qc.sty_gamy-khaki-ray
  QC.Ver:
    repos:
      github.com/eosc-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-crimson-heron.sh
        container: qc.ver_dorky-mustard-owl
timeout: 1800
