config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/eosc-synergy/saps-catalog
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-brass-insect.sh
        container: qc.acc_cozy-teal-rat
  QC.Doc:
    repos:
      github.com/eosc-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-aqua-whippet.sh
        container: qc.doc_droopy-myrtle-dragon
      github.com/eosc-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-teal-chicken.sh
        container: qc.doc_chummy-turquoise-yak
      github.com/eosc-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-pumpkin-fox.sh
        container: qc.doc_silly-razzmatazz-terrier
  QC.Lic:
    repos:
      github.com/eosc-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-mauve-toucan.sh
        container: qc.lic_flaky-amethyst-seal
  QC.Sec:
    repos:
      github.com/eosc-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-taupe-lynx.sh
        container: qc.sec_dorky-turquoise-yak
  QC.Sty:
    repos:
      github.com/eosc-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-coral-bulldog.sh
        container: qc.sty_stinky-cream-numbat
  QC.Ver:
    repos:
      github.com/eosc-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-crimson-wolverine.sh
        container: qc.ver_snazzy-goldenrod-deer
timeout: 1800
