config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-vermilion-cougar.sh
        container: qc.acc_cheeky-celadon-iguana
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-flax-dalmatian.sh
        container: qc.doc_woolly-chartreuse-tarantula
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-red-bobcat.sh
        container: qc.doc_ready-sangria-bobcat
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cyan-chicken.sh
        container: qc.doc_pokey-teal-meerkat
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-gold-ladybird.sh
        container: qc.lic_tacky-vermilion-whippet
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cerise-guppy.sh
        container: qc.sec_pokey-black-bombay
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-purple-llama.sh
        container: qc.sty_stinky-fuchsia-bison
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-bistre-yak.sh
        container: qc.ver_woolly-scarlet-hyena
timeout: 1800
