config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-chocolate-neanderthal.sh
        container: qc.acc_skinny-sangria-kakapo
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-alizarin-moose.sh
        container: qc.doc_homey-bistre-kiwi
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-periwinkle-peccary.sh
        container: qc.doc_trippy-brown-tortoise
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-khaki-otter.sh
        container: qc.doc_stuffy-amaranth-skunk
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-viridian-bat.sh
        container: qc.lic_sleazy-emerald-cuscus
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-smalt-badger.sh
        container: qc.sec_clammy-burgundy-peccary
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-orange-molly.sh
        container: qc.sty_cheeky-peach-quoll
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-denim-penguin.sh
        container: qc.ver_clammy-tangerine-sloth
timeout: 1800
