config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-saffron-wombat.sh
        container: qc.acc_trippy-amethyst-tzu
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-charcoal-avocet.sh
        container: qc.doc_greasy-gold-zorse
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-chartreuse-beagle.sh
        container: qc.doc_snoopy-sangria-bear
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-myrtle-newfoundland.sh
        container: qc.doc_snazzy-thistle-eel
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-brown-lionfish.sh
        container: qc.lic_frumpy-dandelion-weasel
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-seashell-ostrich.sh
        container: qc.sec_stealthy-ruby-elephant
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-chestnut-akbash.sh
        container: qc.sty_shabby-tangerine-macaw
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-rose-dingo.sh
        container: qc.ver_nerdy-dandelion-mole
timeout: 1800
